name: Android CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-platform: "30"
          build-tools: "30.0.2"

      - name: Create local.properties
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties

      - name: Use Gradle version 8.0
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.0
          ./gradlew clean

      - name: Execute unit tests
        id: test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Add comment on test failure
        if: steps.test.outcome == 'failure'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️⚠️⚠️ Las pruebas unitarias han fallado. Por favor, revisa los detalles.'
            });
