name: Android CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d $ANDROID_HOME
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin
          sdkmanager --install "platforms;android-30" "build-tools;30.0.2"

      - name: Create local.properties
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties

      - name: Use Gradle version 8.0
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.0
          ./gradlew clean

      - name: Execute unit tests
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
