name: Android CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Configure Gradle for Java 17
        run: echo "org.gradle.java.home=/opt/hostedtoolcache/Java_Adopt_jdk/17.0.1-1/x64" > gradle.properties

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Use Gradle version 8.0
        run: |
          export JAVA_HOME="/opt/hostedtoolcache/Java_Adopt_jdk/17.0.1-1/x64"
          ./gradlew wrapper --gradle-version 8.0

      - name: Execute unit tests
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
